stages:
    - build-bundle
    - build-docker

build-bundle:
    image: node:12
    only:
        - tags
    stage: build-bundle
    script:
        - cd $CI_PROJECT_DIR
        - yarn
        - yarn build
    artifacts:
        expire_in: 20 min
        paths:
            - dist/*

build-docker:
    image: docker:19.03.5
    only:
        - tags
    stage: build-docker
    variables:
        DOCKER_TLS_CERTDIR: ''
        CONTAINER_RELEASE_IMAGE: 'registry.gitlab.com/konecty/$CI_PROJECT_NAME:$CI_COMMIT_TAG'
    services:
        - docker:19.03.5-dind
    before_script:
        - docker info
    script:
        - cd $CI_PROJECT_DIR
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t $CONTAINER_RELEASE_IMAGE .
        - docker push $CONTAINER_RELEASE_IMAGE
    dependencies:
        - build-bundle
