stages:
	- build-docker

build-docker:
	image: docker:latest
	only:
			- tags
	stage: build-docker
	variables:
			CONTAINER_RELEASE_IMAGE: 'registry.gitlab.com/konecty/$CI_PROJECT_NAME:$CI_COMMIT_TAG'
	services:
			- docker:dind
	before_script:
			- docker info
	script:
			- cd $CI_PROJECT_DIR
			- docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
			- docker build -t $CONTAINER_RELEASE_IMAGE .
			- docker push $CONTAINER_RELEASE_IMAGE
